In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('data/marvel_movies.csv')
df

,titulo,year,duracion,presupuesto,recaudacion,personajes,valoracion
0,Iron Man,2008,126,140,585,"Iron Man, Pepper Potts, Obadiah Stane",7.9
1,The Avengers,2012,143,220,1518,"Iron Man, Capitan America, Thor, Hulk",8.0
2,Black Panther,2018,134,200,1347,"Black Panther, T'Challa, Killmonger, Shuri",7.3
3,Avengers: Infinity War,2018,149,316,2052,"Iron Man, Capitan America, Thor, Thanos, Spide...",7.5
4,Avengers: Endgame,2019,181,356,2798,"Iron Man, Capitan America, Thor, Thanos, Spide...",8.4
5,SpiderMan: No Way Home,2021,148,200,1921,"Spiderman, Doctor Strange, Green Goblin",8.2
6,Guardians of the Galaxy,2014,121,170,773,"Star-Lord, Gamora, Drax, Rocket, Groot",8.0
7,Doctor Strange,2016,115,165,677,"Stephen Strange, Wong, Mordo",7.5
8,Thor: Ragnarok,2017,130,180,854,"Thor, Loki, Hela, Hulk",7.9
9,Captain Marvel,2019,123,152,1128,"Carol Danvers, Nick Fury, Talos",6.8
10,Ant-Man and the Wasp,2018,118,130,622,"Scott Lang, Hope van Dyne, Hank Pym",7.0
11,Guardianes de la Galaxia vol. 2,2017,136,200,863,"Star-Lord, Gamora, Drax, Rocket, Groot, Mantis...",6.7
12,Eternals,2021,156,236,402,"Caballero negro, Ikaris, Ajak, Sprite, Thena, ...",5.4
13,Thor: Love and Thunder,2022,119,250,760,"Gorr, Thor, Zeus, Korg, King Valkyrie, Heimdall",5.3

In [3]:
df.tail()

,titulo,year,duracion,presupuesto,recaudacion,personajes,valoracion
9,Captain Marvel,2019,123,152,1128,"Carol Danvers, Nick Fury, Talos",6.8
10,Ant-Man and the Wasp,2018,118,130,622,"Scott Lang, Hope van Dyne, Hank Pym",7.0
11,Guardianes de la Galaxia vol. 2,2017,136,200,863,"Star-Lord, Gamora, Drax, Rocket, Groot, Mantis...",6.7
12,Eternals,2021,156,236,402,"Caballero negro, Ikaris, Ajak, Sprite, Thena, ...",5.4
13,Thor: Love and Thunder,2022,119,250,760,"Gorr, Thor, Zeus, Korg, King Valkyrie, Heimdall",5.3

In [4]:
df.describe()

              year    duracion  presupuesto  recaudacion  valoracion
count    14.000000   14.000000    14.000000    14.000000   14.000000
mean   2017.142857  135.642857   208.214286  1164.285714    7.278571
std       3.759238   18.341240    64.672166   687.317240    0.964906
min    2008.000000  115.000000   130.000000   402.000000    5.300000
25%    2016.250000  121.500000   166.250000   697.750000    6.850000
50%    2018.000000  132.000000   200.000000   858.500000    7.500000
75%    2019.000000  146.750000   232.000000  1475.250000    7.975000
max    2022.000000  181.000000   356.000000  2798.000000    8.400000

In [6]:
df['year'].value_counts()

year
2018    3
2019    2
2021    2
2017    2
2008    1
2012    1
2014    1
2016    1
2022    1
Name: count, dtype: int64

In [8]:
df.sort_values('valoracion', ascending=False)

,titulo,year,duracion,presupuesto,recaudacion,personajes,valoracion
4,Avengers: Endgame,2019,181,356,2798,"Iron Man, Capitan America, Thor, Thanos, Spide...",8.4
5,SpiderMan: No Way Home,2021,148,200,1921,"Spiderman, Doctor Strange, Green Goblin",8.2
1,The Avengers,2012,143,220,1518,"Iron Man, Capitan America, Thor, Hulk",8.0
6,Guardians of the Galaxy,2014,121,170,773,"Star-Lord, Gamora, Drax, Rocket, Groot",8.0
0,Iron Man,2008,126,140,585,"Iron Man, Pepper Potts, Obadiah Stane",7.9
8,Thor: Ragnarok,2017,130,180,854,"Thor, Loki, Hela, Hulk",7.9
3,Avengers: Infinity War,2018,149,316,2052,"Iron Man, Capitan America, Thor, Thanos, Spide...",7.5
7,Doctor Strange,2016,115,165,677,"Stephen Strange, Wong, Mordo",7.5
2,Black Panther,2018,134,200,1347,"Black Panther, T'Challa, Killmonger, Shuri",7.3
10,Ant-Man and the Wasp,2018,118,130,622,"Scott Lang, Hope van Dyne, Hank Pym",7.0
9,Captain Marvel,2019,123,152,1128,"Carol Danvers, Nick Fury, Talos",6.8
11,Guardianes de la Galaxia vol. 2,2017,136,200,863,"Star-Lord, Gamora, Drax, Rocket, Groot, Mantis...",6.7
12,Eternals,2021,156,236,402,"Caballero negro, Ikaris, Ajak, Sprite, Thena, ...",5.4
13,Thor: Love and Thunder,2022,119,250,760,"Gorr, Thor, Zeus, Korg, King Valkyrie, Heimdall",5.3

In [9]:
df.T

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
titulo,Iron Man,The Avengers,Black Panther,Avengers: Infinity War,Avengers: Endgame,SpiderMan: No Way Home,Guardians of the Galaxy,Doctor Strange,Thor: Ragnarok,Captain Marvel,Ant-Man and the Wasp,Guardianes de la Galaxia vol. 2,Eternals,Thor: Love and Thunder
year,2008,2012,2018,2018,2019,2021,2014,2016,2017,2019,2018,2017,2021,2022
duracion,126,143,134,149,181,148,121,115,130,123,118,136,156,119
presupuesto,140,220,200,316,356,200,170,165,180,152,130,200,236,250
recaudacion,585,1518,1347,2052,2798,1921,773,677,854,1128,622,863,402,760
personajes,"Iron Man, Pepper Potts, Obadiah Stane","Iron Man, Capitan America, Thor, Hulk","Black Panther, T'Challa, Killmonger, Shuri","Iron Man, Capitan America, Thor, Thanos, Spide...","Iron Man, Capitan America, Thor, Thanos, Spide...","Spiderman, Doctor Strange, Green Goblin","Star-Lord, Gamora, Drax, Rocket, Groot","Stephen Strange, Wong, Mordo","Thor, Loki, Hela, Hulk","Carol Danvers, Nick Fury, Talos","Scott Lang, Hope van Dyne, Hank Pym","Star-Lord, Gamora, Drax, Rocket, Groot, Mantis...","Caballero negro, Ikaris, Ajak, Sprite, Thena, ...","Gorr, Thor, Zeus, Korg, King Valkyrie, Heimdall"
valoracion,7.9,8.0,7.3,7.5,8.4,8.2,8.0,7.5,7.9,6.8,7.0,6.7,5.4,5.3

In [10]:
df[df['valoracion']>8]

,titulo,year,duracion,presupuesto,recaudacion,personajes,valoracion
4,Avengers: Endgame,2019,181,356,2798,"Iron Man, Capitan America, Thor, Thanos, Spide...",8.4
5,SpiderMan: No Way Home,2021,148,200,1921,"Spiderman, Doctor Strange, Green Goblin",8.2

In [12]:
df[ (df['valoracion'] > 7.5) & (df['presupuesto'] < 200) ]

,titulo,year,duracion,presupuesto,recaudacion,personajes,valoracion
0,Iron Man,2008,126,140,585,"Iron Man, Pepper Potts, Obadiah Stane",7.9
6,Guardians of the Galaxy,2014,121,170,773,"Star-Lord, Gamora, Drax, Rocket, Groot",8.0
8,Thor: Ragnarok,2017,130,180,854,"Thor, Loki, Hela, Hulk",7.9